### ISSUE TITLE
Uninitialized argument value in prv_open_uri_cb

### ISSUE THREAD

**Issue by phako** [intel/dleyna-renderer#161]
Found by scan-build, only applicablie with #if DLEYNA_LOG_LEVEL & DLEYNA_LOG_LEVEL_DEBUG

Logic error Uninitialized argument value    device.c    prv_open_uri_cb 2968    6   View Report

**Comment by rsbells** [comment]
You forgot to attach report

**Comment by phako** [comment]
Sorry. But you've found and fixed the issue anyway :+1:
